version: '3.8'

services:
  web:
    build: .
    container_name: safe-eval-container
    restart: always
    cap_add:
      - SYS_ADMIN  # Разрешаем cron менять UID
    security_opt:
      - no-new-privileges:true  # Блокируем повышение привилегий внутри контейнера
    ports:
      - "5000:5000"

