version: '3.8'

services:
  ctf-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
  ssh:
    build: ./ssh
    ports:
      - "2222:22"
    privileged: true
    restart: unless-stopped
