version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "5000:80"
    volumes:
      - ./web/src:/var/www/html
    restart: unless-stopped

  ssh:
    build: ./ssh
    ports:
      - "2222:22"
    privileged: true
    restart: unless-stopped

